### ISSUE TITLE
Very slow than the builtin memcpy

### ISSUE THREAD

**Issue by gowthamparuchuru** [skywind3000/FastMemcpy#5]
## gcc version is 4.4.7

# OP:
benchmark(size=32 bytes, times=16777216):
result(dst aligned, src aligned): memcpy_fast=278ms memcpy=85 ms
result(dst aligned, src unalign): memcpy_fast=295ms memcpy=175 ms
result(dst unalign, src aligned): memcpy_fast=299ms memcpy=85 ms
result(dst unalign, src unalign): memcpy_fast=283ms memcpy=179 ms

benchmark(size=64 bytes, times=16777216):
result(dst aligned, src aligned): memcpy_fast=398ms memcpy=123 ms
result(dst aligned, src unalign): memcpy_fast=403ms memcpy=211 ms
result(dst unalign, src aligned): memcpy_fast=386ms memcpy=104 ms
result(dst unalign, src unalign): memcpy_fast=384ms memcpy=195 ms

benchmark(size=512 bytes, times=8388608):
result(dst aligned, src aligned): memcpy_fast=815ms memcpy=223 ms
result(dst aligned, src unalign): memcpy_fast=819ms memcpy=296 ms
result(dst unalign, src aligned): memcpy_fast=924ms memcpy=324 ms
result(dst unalign, src unalign): memcpy_fast=1082ms memcpy=304 ms

benchmark(size=1024 bytes, times=4194304):
result(dst aligned, src aligned): memcpy_fast=881ms memcpy=265 ms
result(dst aligned, src unalign): memcpy_fast=748ms memcpy=292 ms
result(dst unalign, src aligned): memcpy_fast=792ms memcpy=271 ms
result(dst unalign, src unalign): memcpy_fast=918ms memcpy=282 ms

benchmark(size=4096 bytes, times=524288):
result(dst aligned, src aligned): memcpy_fast=365ms memcpy=40 ms
result(dst aligned, src unalign): memcpy_fast=374ms memcpy=81 ms
result(dst unalign, src aligned): memcpy_fast=369ms memcpy=69 ms
result(dst unalign, src unalign): memcpy_fast=378ms memcpy=80 ms

benchmark(size=8192 bytes, times=262144):
result(dst aligned, src aligned): memcpy_fast=391ms memcpy=35 ms
result(dst aligned, src unalign): memcpy_fast=369ms memcpy=67 ms
result(dst unalign, src aligned): memcpy_fast=374ms memcpy=60 ms
result(dst unalign, src unalign): memcpy_fast=417ms memcpy=68 ms

benchmark(size=1048576 bytes, times=2048):
result(dst aligned, src aligned): memcpy_fast=597ms memcpy=162 ms
result(dst aligned, src unalign): memcpy_fast=618ms memcpy=166 ms
result(dst unalign, src aligned): memcpy_fast=604ms memcpy=154 ms
result(dst unalign, src unalign): memcpy_fast=587ms memcpy=155 ms

benchmark(size=4194304 bytes, times=512):
result(dst aligned, src aligned): memcpy_fast=409ms memcpy=195 ms
result(dst aligned, src unalign): memcpy_fast=450ms memcpy=205 ms
result(dst unalign, src aligned): memcpy_fast=440ms memcpy=189 ms
result(dst unalign, src unalign): memcpy_fast=438ms memcpy=200 ms

benchmark(size=8388608 bytes, times=256):
result(dst aligned, src aligned): memcpy_fast=420ms memcpy=219 ms
result(dst aligned, src unalign): memcpy_fast=426ms memcpy=212 ms
result(dst unalign, src aligned): memcpy_fast=431ms memcpy=210 ms
result(dst unalign, src unalign): memcpy_fast=426ms memcpy=209 ms

benchmark random access:
memcpy_fast=6917ms memcpy=1862ms

**Comment by skywind3000** [comment]
compile with `-O2`

**Comment by gowthamparuchuru** [comment]
Sorry my bad... my compilation was wrong...
Now it's better
Thank You.
