### ISSUE TITLE
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)  results

### ISSUE THREAD

**Issue by zhanglistar** [skywind3000/FastMemcpy#7]
➜  FastMemcpy git:(master) ./FastMemcpy
benchmark(size=32 bytes, times=16777216):
result(dst aligned, src aligned): memcpy_fast=37ms memcpy=39 ms
result(dst aligned, src unalign): memcpy_fast=35ms memcpy=38 ms
result(dst unalign, src aligned): memcpy_fast=34ms memcpy=39 ms
result(dst unalign, src unalign): memcpy_fast=42ms memcpy=51 ms

benchmark(size=64 bytes, times=16777216):
result(dst aligned, src aligned): memcpy_fast=34ms memcpy=43 ms
result(dst aligned, src unalign): memcpy_fast=60ms memcpy=60 ms
result(dst unalign, src aligned): memcpy_fast=33ms memcpy=40 ms
result(dst unalign, src unalign): memcpy_fast=34ms memcpy=39 ms

benchmark(size=512 bytes, times=8388608):
result(dst aligned, src aligned): memcpy_fast=121ms memcpy=77 ms
result(dst aligned, src unalign): memcpy_fast=102ms memcpy=63 ms
result(dst unalign, src aligned): memcpy_fast=88ms memcpy=79 ms
result(dst unalign, src unalign): memcpy_fast=88ms memcpy=51 ms

benchmark(size=1024 bytes, times=4194304):
result(dst aligned, src aligned): memcpy_fast=82ms memcpy=41 ms
result(dst aligned, src unalign): memcpy_fast=87ms memcpy=43 ms
result(dst unalign, src aligned): memcpy_fast=88ms memcpy=44 ms
result(dst unalign, src unalign): memcpy_fast=87ms memcpy=44 ms

benchmark(size=4096 bytes, times=524288):
result(dst aligned, src aligned): memcpy_fast=47ms memcpy=27 ms
result(dst aligned, src unalign): memcpy_fast=40ms memcpy=20 ms
result(dst unalign, src aligned): memcpy_fast=38ms memcpy=23 ms
result(dst unalign, src unalign): memcpy_fast=40ms memcpy=22 ms

benchmark(size=8192 bytes, times=262144):
result(dst aligned, src aligned): memcpy_fast=40ms memcpy=22 ms
result(dst aligned, src unalign): memcpy_fast=62ms memcpy=23 ms
result(dst unalign, src aligned): memcpy_fast=57ms memcpy=46 ms
result(dst unalign, src unalign): memcpy_fast=41ms memcpy=47 ms

benchmark(size=1048576 bytes, times=2048):
result(dst aligned, src aligned): memcpy_fast=60ms memcpy=53 ms
result(dst aligned, src unalign): memcpy_fast=61ms memcpy=48 ms
result(dst unalign, src aligned): memcpy_fast=61ms memcpy=52 ms
result(dst unalign, src unalign): memcpy_fast=62ms memcpy=51 ms

benchmark(size=4194304 bytes, times=512):
result(dst aligned, src aligned): memcpy_fast=70ms memcpy=53 ms
result(dst aligned, src unalign): memcpy_fast=66ms memcpy=53 ms
result(dst unalign, src aligned): memcpy_fast=67ms memcpy=57 ms
result(dst unalign, src unalign): memcpy_fast=66ms memcpy=57 ms

benchmark(size=8388608 bytes, times=256):
result(dst aligned, src aligned): memcpy_fast=63ms memcpy=69 ms
result(dst aligned, src unalign): memcpy_fast=64ms memcpy=68 ms
result(dst unalign, src aligned): memcpy_fast=64ms memcpy=71 ms
result(dst unalign, src unalign): memcpy_fast=80ms memcpy=69 ms

benchmark random access:
memcpy_fast=600ms memcpy=531ms

`➜  FastMemcpy git:(master) gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-17ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-HskZEa/gcc-9-9.3.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 
`

**Comment by zhanglistar** [comment]
`➜  FastMemcpy git:(master) ./FastMemcpy_Avx 
benchmark(size=32 bytes, times=16777216):
result(dst aligned, src aligned): memcpy_fast=50ms memcpy=39 ms
result(dst aligned, src unalign): memcpy_fast=48ms memcpy=39 ms
result(dst unalign, src aligned): memcpy_fast=49ms memcpy=59 ms
result(dst unalign, src unalign): memcpy_fast=49ms memcpy=81 ms

benchmark(size=64 bytes, times=16777216):
result(dst aligned, src aligned): memcpy_fast=62ms memcpy=39 ms
result(dst aligned, src unalign): memcpy_fast=64ms memcpy=39 ms
result(dst unalign, src aligned): memcpy_fast=53ms memcpy=38 ms
result(dst unalign, src unalign): memcpy_fast=54ms memcpy=39 ms

benchmark(size=512 bytes, times=8388608):
result(dst aligned, src aligned): memcpy_fast=105ms memcpy=61 ms
result(dst aligned, src unalign): memcpy_fast=105ms memcpy=51 ms
result(dst unalign, src aligned): memcpy_fast=104ms memcpy=51 ms
result(dst unalign, src unalign): memcpy_fast=104ms memcpy=53 ms

benchmark(size=1024 bytes, times=4194304):
result(dst aligned, src aligned): memcpy_fast=84ms memcpy=42 ms
result(dst aligned, src unalign): memcpy_fast=85ms memcpy=42 ms
result(dst unalign, src aligned): memcpy_fast=84ms memcpy=45 ms
result(dst unalign, src unalign): memcpy_fast=85ms memcpy=44 ms

benchmark(size=4096 bytes, times=524288):
result(dst aligned, src aligned): memcpy_fast=40ms memcpy=20 ms
result(dst aligned, src unalign): memcpy_fast=39ms memcpy=20 ms
result(dst unalign, src aligned): memcpy_fast=40ms memcpy=21 ms
result(dst unalign, src unalign): memcpy_fast=40ms memcpy=21 ms

benchmark(size=8192 bytes, times=262144):
result(dst aligned, src aligned): memcpy_fast=41ms memcpy=23 ms
result(dst aligned, src unalign): memcpy_fast=41ms memcpy=23 ms
result(dst unalign, src aligned): memcpy_fast=40ms memcpy=34 ms
result(dst unalign, src unalign): memcpy_fast=46ms memcpy=33 ms

benchmark(size=1048576 bytes, times=2048):
result(dst aligned, src aligned): memcpy_fast=87ms memcpy=45 ms
result(dst aligned, src unalign): memcpy_fast=88ms memcpy=45 ms
result(dst unalign, src aligned): memcpy_fast=98ms memcpy=51 ms
result(dst unalign, src unalign): memcpy_fast=99ms memcpy=50 ms

benchmark(size=4194304 bytes, times=512):
result(dst aligned, src aligned): memcpy_fast=70ms memcpy=51 ms
result(dst aligned, src unalign): memcpy_fast=73ms memcpy=54 ms
result(dst unalign, src aligned): memcpy_fast=71ms memcpy=58 ms
result(dst unalign, src unalign): memcpy_fast=70ms memcpy=59 ms

benchmark(size=8388608 bytes, times=256):
result(dst aligned, src aligned): memcpy_fast=73ms memcpy=71 ms
result(dst aligned, src unalign): memcpy_fast=71ms memcpy=69 ms
result(dst unalign, src aligned): memcpy_fast=69ms memcpy=69 ms
result(dst unalign, src unalign): memcpy_fast=70ms memcpy=69 ms

benchmark random access:
memcpy_fast=626ms memcpy=548ms
`

**Comment by alexey-milovidov** [comment]
Also look at the comment: https://github.com/skywind3000/FastMemcpy/issues/6#issuecomment-723501146
